services:
  mysql:
    image: mysql:8.0.43
    container_name: sv_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-sv
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_v2:/var/lib/mysql
    networks:
      - sv_network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sv_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: test-sv

      APP_ENV: local
      APP_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sv_network
    volumes:
      - ./logs:/root/logs

networks:
  sv_network:
    driver: bridge

volumes:
  mysql_data_v2:
    driver: local