services:
  postgres:
    image: postgres:16-alpine
    container_name: sv_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test-sv
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sv_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test-sv"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sv_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: test-sv
      DB_SSLMODE: disable

      APP_ENV: local
      APP_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sv_network
    volumes:
      - ./logs:/root/logs

networks:
  sv_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local