// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"gorm.io/gorm"
	"test-be/config"
	"test-be/internal/handler"
	"test-be/internal/repositories"
	"test-be/internal/services"
)

// Injectors from app_injector.go:

func InitializeApp() (*AppContainer, error) {
	db := config.ConnectGormDB()
	articleRepository := repositories.NewArticleRepository()
	articleService := services.NewArticleService(db, articleRepository)
	articleHandler := handler.NewArticleHandler(articleService)
	appContainer, err := NewAppContainer(db, articleHandler)
	if err != nil {
		return nil, err
	}
	return appContainer, nil
}

// app_injector.go:

type AppContainer struct {
	DB *gorm.DB
	//
	ArticleHandler *handler.ArticleHandler
}

func NewAppContainer(
	db *gorm.DB,

	articleHandler *handler.ArticleHandler,
) (*AppContainer, error) {
	return &AppContainer{
		DB: db,

		ArticleHandler: articleHandler,
	}, nil
}
